/* eslint-disable react/no-unescaped-entities */
import { Page, Text, View } from '@react-pdf/renderer'
import { tw } from './document-pdf'

function LawsPage(): JSX.Element {
  return (
    <Page style={tw('p-10 font-sans')} size={'A4'}>
      <View>
        <Text style={tw('text-base')}>
          Between the client designated on the front and the property owner, the following has been agreed:
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE I: RENTAL AGREEMENT
        </Text>
        <Text style={tw('text-base')}>
          The rent is payable in advance. A security deposit is mandatory and cannot be used to extend the rental period without the prior consent of the owner. The tenant agrees to notify the owner 48 hours before the expiration of the current rental period. The tenant agrees to vacate the property on the agreed-upon date and time specified in this contract. Any changes must be communicated to the owner.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE II: USE OF PROPERTY
        </Text>
        <Text style={tw('text-base')}>
          The rental is personal and is non-transferable. The tenant agrees not to sublet the property, not to use the property for illegal activities, and not to engage in any activities that may cause damage to the property.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE III: MAINTENANCE AND REPAIRS
        </Text>
        <Text style={tw('text-base')}>
          The tenant agrees to maintain the property in good condition and to report any damages or necessary repairs to the owner immediately. The tenant is responsible for any damages caused by negligence or misuse. Regular wear and tear are the owner's responsibility.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE IV: SECURITY DEPOSIT
        </Text>
        <Text style={tw('text-base')}>
          The security deposit will be held by the owner to cover any damages, unpaid rent, or other expenses incurred during the tenancy. The deposit will be returned to the tenant within 30 days of vacating the property, provided no deductions are necessary.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE V: INSURANCE
        </Text>
        <Text style={tw('text-base')}>
          The tenant is responsible for obtaining renter's insurance to cover personal belongings and liability. The owner is not liable for any loss or damage to the tenant's property.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE VI: UTILITIES AND SERVICES
        </Text>
        <Text style={tw('text-base')}>
          The tenant is responsible for the payment of all utilities and services unless otherwise specified in the rental agreement. The tenant agrees to keep the utilities active for the duration of the tenancy.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE VII: RESPONSIBILITY
        </Text>
        <Text style={tw('text-base')}>
          The tenant remains solely responsible for any fines, penalties, or legal actions resulting from their use of the property. The tenant agrees not to abandon the property under any circumstances and to notify the owner immediately if they intend to vacate the property before the end of the rental period.
        </Text>
        <Text style={[tw('font-semibold uppercase m-0'), { fontSize: 12 }]}>
          ARTICLE VIII: LEGAL JURISDICTION
        </Text>
        <Text style={tw('text-base')}>
          In the event of any disputes arising from this rental agreement, only the courts within the jurisdiction where the property is located shall be competent.
        </Text>
      </View>
      <View style={tw('flex justify-between mt-5')}>
        <Text
          style={tw('text-center text-base')}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
        />
        <Text style={tw('text-right text-sm font-semibold m-0 p-0')}>Generated by Property-Rental</Text>
      </View>
    </Page>
  )
}

export default LawsPage
